### ISSUE TITLE
ShopifyAPI::FulfillmentService returns empty list

### ISSUE THREAD

**Issue by NafaaBout** [Shopify/shopify_api#229] opened 2015-12-05 21:33 UTC
I am building an Shopify app. When a user installs the app on his shop, I need to get the list of fulfilment services that are active on his shop, mainly the amazon marketplace web. The app uses ShopifyAPP and ShopifyAPI gems, so I tried to call ShopifyAPI::FulfillmentService.all. but it returns an empty list. I tried it on two shops with different fulfillment services activated, and got the same results. I tried to set the scope to 'all', but got the same results as well. 
Is this a bug or I am doing something wrong/

**Comment by kevinhughes27** [comment] 2015-12-07 14:46
The Fulfillment Service API only returns fulfillment services that were created by that api client by design. Can you elaborate a bit more on what you need this for (you can email me at kevin.hughes@shopify.com if you'd rather not post it on a public forum).

You could also get this info by querying variants and looking at the fulfillment services they are actually using but that might not work 100% depending on what you need this for.

I am going to close this issue though because this isn't a specific problem with the code in this repo but the api in general. I'd recommend also making a post on the forum https://ecommerce.shopify.com/c/shopify-apis-and-technology

**Closed by kevinhughes27** 2015-12-07 14:46 UTC
