### ISSUE TITLE
cancelling pending charges

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_api#196] opened 2015-07-03 18:11 UTC
I have a shop with 16 pending charges. None activated. Say I want to remove them:

    ShopifyAPI::RecurringApplicationCharge.all.each { |c| c.cancel  };nil
ActiveResource::ResourceInvalid: Failed.  Response code = 422.  Response message = Unprocessable Entity.

What is the correct way to get rid of these?

**Comment by joshubrown** [comment] 2015-07-04 05:31
Thanks for creating the issue. It's not possible to cancel a pending charge right now. Do you think we should add this? Pending charges expire after 48 hours.

**Comment by resistorsoftware** [comment] 2015-07-04 06:30
I think the presence of more than one pending charge is leading to a bug I see. Why else would I have a client with 16 of them, and her claim that Shopify is not asking her for approval on an App. She is creating them, but the redirect to the confirmation URL is not happening.

**Comment by joshubrown** [comment] 2015-08-11 15:38
Are you able to reproduce the issue?

**Comment by resistorsoftware** [comment] 2015-08-11 15:57
You mean find merchants in my Apps where a quick iteration of the RecurringApplicationCharges shows N in a state of pending and none in a state of accepted, declined or cancelled? Yes... I can say that is still an issue...

**Comment by orenmazor** [comment] 2016-07-28 20:31
Looks like I had just made a duplicate of this in #292.

this doesn't affect production code for me, but it would super simplify my test suite, as I could just clear the charges I'm throwing at my test shops.

alternatively, being able to mark a RecurringApplicationCharge as a test charge should allow me to automatically mark it as accepted.

**Comment by joshubrown** [comment] 2016-07-28 21:23
Sorry @orenmazor — there is no cancelling them at the moment.

**Closed by joshubrown** 2016-07-28 21:23 UTC

**Comment by orenmazor** [comment] 2016-07-28 22:07
![booo](https://cloud.githubusercontent.com/assets/384279/17231128/181ef774-54ee-11e6-9439-58b610a9ee08.jpg)
